background img
galinadimina/final-project-js pull request #5
Opened 2020-10-12 20:21 UTC by galinadimina

2020-10-13 10:12 UTC, MrTim commented
@galinadimina General comment - please make a meaningful branch names and provide a description when you creating pull request. This will help us and you a lot :)

2020-10-13 10:17 UTC, MrTim requested changes
Left code comment. Please take a look.

2020-10-13 10:17 UTC, MrTim commented on index.html
> +              <div class="card"></div>
you can create it a bit differently. Since at the end you will need to dynamically create a list of movies (because they will come from api) you can already prepare for that.
You will need to do the following:
- create an array with 4 movies
- iterate over it
- create this cards with movies dynamically with js code

And then it will be much easier for you to switch for api.

2020-10-13 10:17 UTC, MrTim commented on index.html
> + <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></
use the same indentation as above.

2020-10-13 10:17 UTC, MrTim commented on style.css
> +  /* background-color: #F6DDCC ; */
try not to leave commented code in something you're about to merge to master.

2020-10-13 10:17 UTC, MrTim commented on style.css
> +
you don't need this empty line. The same below

2020-10-13 10:17 UTC, MrTim commented on style.css
> + cursor: pointer;
indentation here.
If you wan't you can install Prettier for VSCode and it will take case about indentation and code formatting for you.

2020-10-17 14:12 UTC, merged

2020-10-18 10:36 UTC, MrTim commented
@galinadimina just want to clarify, why you merged this branch to master?

2020-10-18 16:45 UTC, galinadimina commented
> @galinadimina just want to clarify, why you merged this branch to master?

I should not do this. Am I right?
Probably that was my bad and I've misunderstood the given information.
I was thinking that I have to merge the branch to the main one and delete the used branch...
Probably, I  miserably failed.

2020-10-19 07:28 UTC, MrTim commented
@galinadimina rule is the following - don't merge if no one approved it yet. And ONLY after you got at least one approval on your PR you can merge it to master. So please do so next time :)